<a href="https://colab.research.google.com/github/20240609-lab/Data-Science/blob/main/week11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/6_titanic_data.csv")

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df[['Fare','Age']]

        Fare   Age
0     7.2500  22.0
1    71.2833  38.0
2     7.9250  26.0
3    53.1000  35.0
4     8.0500  35.0
..       ...   ...
886  13.0000  27.0
887  30.0000  19.0
888  23.4500   NaN
889  30.0000  26.0
890   7.7500  32.0

[891 rows x 2 columns]

In [ ]:
data = {'name':['Anna','bob','chris'],
        'age': [20,22,21],
        'score':[85,90,78]
        }

students = pd.DataFrame(data)
students

In [ ]:
odd_numbers = []
even_numbers = []

for i in range(1, 101):
    if i % 2 == 0:
        even_numbers.append(i)
    else:
        odd_numbers.append(i)

odd_even_df = pd.DataFrame({
    '홀수': odd_numbers, '짝수': even_numbers
})

display(odd_even_df)

    홀수   짝수
0    1    2
1    3    4
2    5    6
3    7    8
4    9   10
5   11   12
6   13   14
7   15   16
8   17   18
9   19   20
10  21   22
11  23   24
12  25   26
13  27   28
14  29   30
15  31   32
16  33   34
17  35   36
18  37   38
19  39   40
20  41   42
21  43   44
22  45   46
23  47   48
24  49   50
25  51   52
26  53   54
27  55   56
28  57   58
29  59   60
30  61   62
31  63   64
32  65   66
33  67   68
34  69   70
35  71   72
36  73   74
37  75   76
38  77   78
39  79   80
40  81   82
41  83   84
42  85   86
43  87   88
44  89   90
45  91   92
46  93   94
47  95   96
48  97   98
49  99  100

In [ ]:
df.shape # 행 & 열

(891, 12)

In [ ]:
df = pd.read_csv(path)
data = pd.read_csv(path)

df.head()
data.head()

NameError: name 'path' is not defined

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
print(f'평균 : {df['Fare'].mean()} / 중앙값 : {df['Fare'].median()}')

평균 : 32.204207968574636 / 중앙값 : 14.4542

In [ ]:
print(f'{df['Fare'].sum()}')

28693.9493

In [ ]:
print(f'{df['Age'].sum()/len(df['Age'])}')

23.79929292929293

In [ ]:
total = 0
count = 0

for fare in df['Fare']:
  total += fare
  count += 1

avr = total / count
print(f'평균 요금: {avr:.2f}')

평균 나이 : 32.20

In [ ]:
total = 0
count = 0

for fare in df['Fare']:
  total += fare
  count += 1

if count > 0:
    avr = total / count
    print(f'평균 요금: {avr:.2f}')
else:
    print('Fare 데이터가 없습니다.')

평균 요금: 32.20

In [ ]:
df['Pclass'].value_counts(normalize=True)

Pclass
3    0.551066
1    0.242424
2    0.206510
Name: proportion, dtype: float64

In [ ]:
df[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df[:101]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S
100,101,0,3,"Petranec, Miss Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [ ]:
df.loc[0:4, ["Name","Sex","Age"]]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                              Heikkinen, Miss Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [ ]:
df.loc[0,'Name']

'Braund, Mr. Owen Harris'

In [ ]:
df.iloc[0:2,1:3]

   Survived  Pclass
0         0       3
1         1       1

In [ ]:
df.loc[0:1,['Survived','Pclass']]

   Survived  Pclass
0         0       3
1         1       1